"""
GitHub Integration — OmniSight Backend (Week 3)

PyGithub se automatically branch banata hai, fix commit karta hai,
aur PR open karta hai — sirf un reports ke liye jo DOM cross-check
pass kar chuke hain (trustworthy).
"""

import os
import time
import logging
from dotenv import load_dotenv
from github import Github, Auth, GithubException

load_dotenv()

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("github_integration")

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GITHUB_REPO = os.getenv("GITHUB_REPO")


def get_repo():
    """GitHub client authenticate karo aur repo object return karo."""
    if not GITHUB_TOKEN or not GITHUB_REPO:
        raise ValueError(
            "GITHUB_TOKEN or GITHUB_REPO missing. Check your .env file."
        )

    auth = Auth.Token(GITHUB_TOKEN)
    g = Github(auth=auth)
    repo = g.get_repo(GITHUB_REPO)
    return repo


def create_branch(base_branch: str = "backend-fastapi") -> str:
    """
    Naya branch banao naming pattern: fix/bug-{timestamp}

    Returns: naye branch ka naam
    """
    repo = get_repo()

    timestamp = int(time.time())
    new_branch_name = f"fix/bug-{timestamp}"

    try:
        base_ref = repo.get_branch(base_branch)
        base_sha = base_ref.commit.sha

        repo.create_git_ref(
            ref=f"refs/heads/{new_branch_name}",
            sha=base_sha,
        )

        logger.info(f"Branch created: {new_branch_name} (from {base_branch})")
        return new_branch_name

    except GithubException as e:
        logger.error(f"Failed to create branch: {e}")
        raise


def commit_fix(branch_name: str, file_path: str, new_content: str, commit_message: str):
    """
    Ek file ko diye gaye branch pe update/create karo.

    Args:
        branch_name: jis branch pe commit karna hai (create_branch se aaya)
        file_path: repo ke andar file ka path
        new_content: poori file ka naya content (string)
        commit_message: commit ka message

    Returns: commit object
    """
    repo = get_repo()

    try:
        try:
            existing_file = repo.get_contents(file_path, ref=branch_name)
            result = repo.update_file(
                path=file_path,
                message=commit_message,
                content=new_content,
                sha=existing_file.sha,
                branch=branch_name,
            )
            logger.info(f"File updated: {file_path} on {branch_name}")
        except GithubException:
            result = repo.create_file(
                path=file_path,
                message=commit_message,
                content=new_content,
                branch=branch_name,
            )
            logger.info(f"File created: {file_path} on {branch_name}")

        return result["commit"]

    except GithubException as e:
        logger.error(f"Failed to commit fix: {e}")
        raise


def open_pull_request(
    branch_name: str,
    title: str,
    body: str,
    base_branch: str = "backend-fastapi",
):
    """
    branch_name se base_branch mein PR kholo.

    Returns: PullRequest object
    """
    repo = get_repo()

    try:
        pr = repo.create_pull(
            title=title,
            body=body,
            head=branch_name,
            base=base_branch,
        )

        logger.info(f"Pull Request opened: {pr.html_url}")
        return pr

    except GithubException as e:
        logger.error(f"Failed to open PR: {e}")
        raise


def create_fix_pr(bug_report: dict, base_branch: str = "backend-fastapi"):
    """
    End-to-end helper: branch bano, fix commit karo, PR kholo.

    bug_report ek dict hai (Action Engine se aata hai). Handles both:
    - naya structured format: fix = {"selector": ..., "css_changes": [...], "explanation": ...}
    - purana plain-string format: fix = "some text"
    """
    branch_name = create_branch(base_branch)

    fix = bug_report.get("fix", {})

    if isinstance(fix, dict):
        css_summary = "\n".join(
            f"  - `{c['property']}: {c['value']}`"
            for c in fix.get("css_changes", [])
        )
        fix_description = (
            f"**Selector:** `{fix.get('selector', 'unknown')}`\n\n"
            f"**CSS Changes:**\n{css_summary}\n\n"
            f"**Explanation:** {fix.get('explanation', '')}"
        )
    else:
        fix_description = str(fix)

    commit_message = f"fix: {bug_report.get('description', 'UI bug fix')}"

    proof_content = f"""# Auto-generated fix proof

**Bug:** {bug_report.get('description')}
**Severity:** {bug_report.get('severity_level')}
**Confidence:** {bug_report.get('confidence_score')}

## Suggested Fix

{fix_description}
"""

    commit_fix(
        branch_name=branch_name,
        file_path=f"fixes/{branch_name}.md",
        new_content=proof_content,
        commit_message=commit_message,
    )

    pr = open_pull_request(
        branch_name=branch_name,
        title=f"Auto-fix: {bug_report.get('description', 'UI bug')[:60]}",
        body=f"**Auto-generated by OmniSight**\n\n{proof_content}",
        base_branch=base_branch,
    )

    return pr


# -------------------------------------------------
# Test — python github_integration.py
# -------------------------------------------------
if __name__ == "__main__":
    print("Testing full fix -> PR flow...")

    sample_bug = {
        "bug_found": True,
        "description": "The 'Add to cart' button for the Sauce Labs Fleece Jacket is clipped and not fully visible.",
        "severity_level": "Major",
        "confidence_score": 0.95,
        "fix": {
            "selector": "button.add-to-cart",
            "css_changes": [
                {"property": "max-width", "value": "100px"},
                {"property": "margin-right", "value": "10px"},
            ],
            "explanation": "Reducing the button width and adding margin-right ensures the button is fully visible.",
        },
    }

    try:
        pr = create_fix_pr(sample_bug)
        print(f"✅ PR opened: {pr.html_url}")
    except Exception as e:
        print(f"❌ Error: {e}")